apiVersion: v1
name: frontend
version: 0.2.16
apiVersion: v2
dependencies:
- name: elasticsearch
  version: 7.4.1
  repository: https://helm.elastic.co
  condition: elasticsearch.enabled
- name: rabbitmq
  version: 6.17.x
  repository: '@stable'
  condition: rabbitmq.enabled
