apiVersion: v1
name: frontend
version: 0.2.20
apiVersion: v2
dependencies:
- name: elasticsearch
  version: 7.4.1
  repository: https://helm.elastic.co
  condition: elasticsearch.enabled
- name: rabbitmq
  version: 6.17.x
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: rabbitmq.enabled
- name: silta-release
  version: 0.1.1
  repository: file://../silta-release

