apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx
  annotations:
    kubernetes.io/ingress.class: traefik
    {{- if .Values.ssl.enabled }}
    traefik.ingress.kubernetes.io/frontend-entry-points: "http,https"
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    traefik.ingress.kubernetes.io/frontend-entry-points: "http"
    ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
  labels:
    {{ include "frontend.release_labels" . | indent 4 }}
spec:
  {{- if .Values.ssl.enabled }}
  tls:
  - secretName: {{ .Release.Name }}-tls
  {{- end }}
  rules:
  - host: {{ template "frontend.domain" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-nginx
          servicePort: 80
---
{{- range $index, $domain := .Values.exposeDomains }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-nginx-{{ $index }}
  annotations:
    kubernetes.io/ingress.class: traefik
    {{- if $domain.ssl }}
    {{- if $domain.ssl.enabled }}
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- else }}
    traefik.ingress.kubernetes.io/frontend-entry-points: http
    ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
  labels:
    {{ include "frontend.release_labels" $ | indent 4 }}
spec:
  {{- if $domain.ssl }}
  {{- if $domain.ssl.enabled }}
  tls:
  - secretName: {{ $.Release.Name }}-tls-{{ $index }}
  {{- end }}
  {{- end }}
  rules:
  - host: {{ $domain.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Release.Name }}-nginx
          servicePort: 80
---
{{- end }}

