{{- range $serviceName, $service := .Values.services }}
{{ if $service.cron }}
{{- range $jobName, $job := $service.cron }}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-{{ $jobName }}
  labels:
    {{- include "frontend.release_labels" $ | nindent 4 }}
spec:
  schedule: {{ $job.schedule | replace "~" (randNumeric 1) | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "frontend.release_labels" $ | nindent 12 }}
        spec:
          containers:
          - name: {{ $jobName }}-cron
            image: {{ $service.image | quote }}
            volumeMounts:
              {{ if $service.mounts }}
              {{- range $index, $mountName := $service.mounts -}}
              {{ $mount := (index $.Values.mounts $mountName) }}
              {{- if eq $mount.enabled true }}
              - name: frontend-{{ $mountName }}
                mountPath: {{ $mount.mountPath }}
              {{- end }}
              {{- end }}
              {{- end }}
            env:
            {{- range $key, $val := $service.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- if $.Values.elasticsearch.enabled }}
            - name: ELASTICSEARCH_HOST
              value: {{ $.Release.Name }}-es
            {{- end }}
            command: ["/bin/sh", "-c"]
            args:
              - |
                 set -ex
                 {{ $job.command | nindent 18 }}
            resources:
              {{ if $service.resources -}}
              {{ merge $service.resources $.Values.serviceDefaults.resources | toYaml | nindent 14 }}
              {{ else -}}
              {{ $.Values.serviceDefaults.resources | toYaml | nindent 14 }}
              {{- end }}
          volumes:
            {{ if $service.mounts }}
            {{- range $index, $mountName := $service.mounts -}}
            {{ $mount := (index $.Values.mounts $mountName) }}
            {{- if eq $mount.enabled true }}
            - name: frontend-{{ $mountName }}
              persistentVolumeClaim:
                claimName: {{ $.Release.Name }}-{{ $mountName }}
            {{- end }}
            {{- end }}
            {{- end }}
          restartPolicy: Never
---
{{- end }}
{{- end }}
{{- end }}
