version: 2.1

orbs:
  silta: silta/silta@dev:master

workflows:
  version: 2
  build_deploy:
    jobs:
      - silta/frontend-build-deploy: &build-deploy
          name: 'Silta build & deploy'
          
          # Use a local chart during development. 
          # Don't copy this! We only use following 2 lines for chart development in this repository.
          chart_name: './chart'
          chart_repository: ''

          pre-steps:
            - run: |
                echo "export FOO='bar'" >> $BASH_ENV
          codebase-build:
            - run: |
                echo $FOO

            - silta/npm-install-build:
                path: './hello'
                build-command: ''
            - silta/npm-install-build:
                path: './world'
                build-command: ''
          image_build_steps:
            - silta/build-docker-image:
                dockerfile: 'silta/hello.Dockerfile'
                path: '.'
                identifier: 'hello'
            - silta/build-docker-image:
                dockerfile: 'silta/world.Dockerfile'
                path: '.'
                identifier: 'world'
          context: 'global_nonprod'
          filters:
            branches:
              ignore: 'production'
      - silta/frontend-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *build-deploy
          name: Silta build & deploy production
          silta_config: silta/silta.yml,silta/silta-prod.yml
          context: silta_finland    
          filters:
            branches:
              only: production
