version: 2.1

orbs:
  silta: silta/silta@dev:master

executors:
  silta-latest:
    docker:
      - image: wunderio/silta-circleci:latest
  node12:
    docker:
      - image: eu.gcr.io/silta-images/cicd:circleci-php7.3-node12-composer1-v0.1

jobs:
  validate:
    executor: node12
    steps:
      - checkout
      - run:
          name: Helm unit tests
          command: helm unittest ./charts/frontend --helm3
      # - run:
      #     name: Helm lint
      #     command: helm lint ./charts/frontend

workflows:
  version: 2
  build_deploy:
    jobs:
      - validate:
          name: 'Validate frontend chart'

      - silta/frontend-build-deploy: &build-deploy
          requires:
            - 'Validate frontend chart'
          name: 'Silta build & deploy'

          executor: node12
          
          # Use a local chart during development. 
          # Don't copy this! We only use following 2 lines for chart development in this repository.
          chart_name: './charts/frontend'
          chart_repository: ''
          
          codebase-build:
            # - silta/npm-install-build:
            #     build-command: ''
            - silta/npm-install-build:
                path: './hello'
                build-command: ''
            - silta/npm-install-build:
                path: './world'
                build-command: ''
          image_build_steps:
            - silta/build-docker-image:
                dockerfile: 'silta/hello.Dockerfile'
                path: '.'
                identifier: 'hello'
            - silta/build-docker-image:
                dockerfile: 'silta/world.Dockerfile'
                path: '.'
                identifier: 'world'
            - run:
                name: Add elastic repo for elasticsearch
                command: helm repo add elastic https://helm.elastic.co
            - run:
                name: Build local helm dependencies
                command: helm dependency build ./charts/frontend
            - run:
                name: Dry-run helm install
                command: helm install --dry-run --generate-name ./charts/frontend --values charts/frontend/test.values.yaml
          context: silta_dev
          filters:
            branches:
              ignore:
                - production
                - /feature\/test\/.*/
                - /feature\/aws\/.*/

      - silta/frontend-build-deploy:
          # Extend the build-deploy configuration for the test cluster deployments
          <<: *build-deploy
          name: Silta build & deploy to test cluster
          silta_config: silta/silta.yml,silta/silta-test.yml
          context: silta_test
          filters:
            branches:
              only: 
                - feature\/test\/.*/

      - silta/frontend-build-deploy:
          # Extend the build-deploy configuration for the aws cluster deployments
          <<: *build-deploy
          name: Silta build & deploy to aws cluster
          silta_config: silta/silta.yml,silta/silta-aws.yml
          context: silta_aws
          filters:
            branches:
              only: 
                - /feature\/aws\/.*/

      - silta/frontend-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *build-deploy
          name: Silta build & deploy production
          silta_config: silta/silta.yml,silta/silta-prod.yml
          context: silta_finland    
          filters:
            branches:
              only: production
