{{- if .Values.backup.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup
  labels:
    name: {{ .Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-backup
    cronjob-type: backup
spec:
  schedule: {{ .Values.backup.schedule | replace "~" (randNumeric 1) | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      backoffLimit: 2
      template:
        spec:
          enableServiceLinks: false
          initContainers:
            - name: backup-linking
              image: busybox:1.33.0
              command: ["/bin/sh", "-c"]
              args:
                - |
                  {{- include "frontend.backup.make-destination-path" . | nindent 18 }}
              volumeMounts:
                {{- range $index, $mount := $.Values.mounts }}
                {{- if eq $mount.enabled true }}
                - name: frontend-{{ $index }}
                  mountPath: /backup_source/{{ $index }}
                {{- end }}
                {{- end }}
                - name: {{ .Release.Name }}-backup
                  mountPath: /backups
                - mountPath: /shared
                  name: shared-data
          containers:
          - name: backup
            image: busybox:1.33.0
            volumeMounts:
              {{- range $index, $mount := $.Values.mounts -}}
              {{- if eq $mount.enabled true }}
              - name: frontend-{{ $index }}
                mountPath: /backup_source/{{ $index }}
              {{- end }}
              {{- end }}
              - name: {{ $.Release.Name }}-backup
                mountPath: /backups
              - mountPath: /shared
                name: shared-data
            command: ["/bin/sh", "-c"]
            args:
              - |
                sleep 50000;
          {{- range $index, $service := .Values.services }}
          - name: {{ $index }}
            image: {{ $service.image | quote }}
            env:
            {{- include "services.env" (dict "Values" $.Values "Release" $.Release "service" $service) | nindent 12 }}
            {{- range $key, $val := $service.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            volumeMounts:
              - mountPath: /shared
                name: shared-data
              {{ if $service.mounts }}
              {{- range $index, $mountName := $service.mounts -}}
              {{ $mount := (index $.Values.mounts $mountName) }}
              {{- if eq $mount.enabled true }}
              - name: frontend-{{ $mountName }}
                mountPath: {{ $mount.mountPath }}
              {{- end }}
              {{- end }}
              {{- end }}
          {{- end }}
          restartPolicy: Never
          volumes:
            - name: shared-data
              emptyDir:
                sizeLimit: 10M
            {{- range $index, $service := .Values.services }}
            {{- if $service.mounts -}}
            {{- range $index, $mountName := $service.mounts -}}
            {{ $mount := (index $.Values.mounts $mountName) }}
            {{- if eq $mount.enabled true }}
            - name: frontend-{{ $mountName }}
              persistentVolumeClaim:
                claimName: {{ $.Release.Name }}-{{ $mountName }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- range $index, $mount := $.Values.mounts }}
            - name: frontend-{{ $index }}
              persistentVolumeClaim:
                claimName: {{ $.Release.Name }}-{{ $index }}
            {{- end }}
            - name: {{ .Release.Name }}-backup
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-backup
{{- end }}

---
