apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx
  annotations:
    kubernetes.io/ingress.class: traefik
    {{- if .Values.ssl.enabled }}
    traefik.ingress.kubernetes.io/frontend-entry-points: "http,https"
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    traefik.ingress.kubernetes.io/frontend-entry-points: "http"
    ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}

    {{- if (index .Values "silta-release").downscaler.enabled }}
    auto-downscale/last-update: {{ dateInZone "2006-01-02T15:04:05.999Z" (now) "UTC" }}
    auto-downscale/label-selector: "release={{ .Release.Name }}"
    auto-downscale/services: {{ .Release.Name }}-nginx
    {{- end }}
  labels:
    {{ include "frontend.release_labels" . | indent 4 }}
spec:
  {{- if .Values.ssl.enabled }}
  tls:
  - secretName: {{ .Release.Name }}-tls
  {{- range $index, $prefix := .Values.domainPrefixes }}
  - secretName: {{ $.Release.Name }}-tls-p{{ $index }}
  {{- end }}
  {{- end }}
  rules:
  - host: {{ template "frontend.domain" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-nginx
          servicePort: 80
{{- range $index, $prefix := .Values.domainPrefixes }}
  - host: {{$prefix}}.{{ template "frontend.domain" $ }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Release.Name }}-nginx
          servicePort: 80
{{- end }}
---
{{- range $index, $domain := .Values.exposeDomains }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-nginx-{{ $index }}
  annotations:
    kubernetes.io/ingress.class: traefik
    {{- if $domain.ssl }}
    {{- if $domain.ssl.enabled }}
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- else }}
    traefik.ingress.kubernetes.io/frontend-entry-points: http
    ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
  labels:
    {{ include "frontend.release_labels" $ | indent 4 }}
spec:
  {{- if $domain.ssl }}
  {{- if $domain.ssl.enabled }}
  tls:
  - secretName: {{ $.Release.Name }}-tls-{{ $index }}
  {{- end }}
  {{- end }}
  rules:
  - host: {{ $domain.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Release.Name }}-nginx
          servicePort: 80
---
{{- end }}

