apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    {{ include "frontend.release_labels" . | indent 4 }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
  selector:
    {{ include "frontend.release_labels" . | indent 4 }}
    deployment: frontend
