apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    {{ include "frontend.release_labels" . | indent 4 }}
  annotations:
    auto-downscale/down: "false"
    {{- if .Values.cluster }}
    {{- if eq .Values.cluster.type "gke" }}
    cloud.google.com/backend-config: '{"ports": {"8080":"{{ .Release.Name }}-nginx"}}'
    {{- end }}
    {{- if .Values.cluster.vpcNative }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
    {{- end }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  # We explicitly unset this, in case the application is currently downscaled.
  externalName: null
  ports:
    - port: 80
      targetPort: 8080
  selector:
    {{ include "frontend.release_labels" . | indent 4 }}
    deployment: frontend
