{{- range $serviceName, $service := .Values.services }}
{{ if $service.cron }}
{{- range $jobName, $job := $service.cron }}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-{{ $jobName }}
  labels:
    {{- include "frontend.release_labels" $ | nindent 4 }}
spec:
  schedule: {{ $job.schedule | replace "~" (randNumeric 1) | quote }}
  concurrencyPolicy: {{ default "Forbid" $job.concurrencyPolicy }}
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      parallelism: {{ default 1 $job.parallelism }}
      template:
        metadata:
          labels:
            {{- include "frontend.release_labels" $ | nindent 12 }}
        spec:
          enableServiceLinks: false
          containers:
          - name: {{ $jobName }}-cron
            image: {{ $service.image | quote }}
            volumeMounts:
              {{ if $service.mounts }}
              {{- range $index, $mountName := $service.mounts -}}
              {{ $mount := (index $.Values.mounts $mountName) }}
              {{- if eq $mount.enabled true }}
              - name: frontend-{{ $mountName }}
                mountPath: {{ $mount.mountPath }}
              {{- end }}
              {{- end }}
              {{- end }}
            env:
            {{- range $key, $val := $service.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            - name: 'PORT'
              value: {{ default $.Values.serviceDefaults.port $service.port | quote }}
            - name: 'ENVIRONMENT_DOMAIN'
              value: {{ template "frontend.domain" $ }}
            - name: 'RELEASE_NAME'
              value: {{ $.Release.Name | quote }}
            {{- range $index, $service := $.Values.services }}
            - name: "{{ $index }}_HOST"
              value: "{{ $.Release.Name }}-{{ $index }}:{{ default $.Values.serviceDefaults.port $service.port }}"
            {{- end }}
            {{- if $.Values.elasticsearch.enabled }}
            - name: ELASTICSEARCH_HOST
              value: {{ $.Release.Name }}-es
            {{- end }}
            {{- if $.Values.rabbitmq.enabled }}
            - name: RABBITMQ_HOST
              value: {{ $.Release.Name }}-rabbitmq
            {{- end }}
            command: ["/bin/sh", "-c"]
            args:
              - |
                 set -ex
                 echo "starting cron run"
                 {{ $job.command | nindent 18 }}
                 echo "cron run completed"
            resources:
              {{ if $service.resources -}}
              {{ merge $service.resources $.Values.serviceDefaults.resources | toYaml | nindent 14 }}
              {{ else -}}
              {{ $.Values.serviceDefaults.resources | toYaml | nindent 14 }}
              {{- end }}
          volumes:
            {{ if $service.mounts }}
            {{- range $index, $mountName := $service.mounts -}}
            {{ $mount := (index $.Values.mounts $mountName) }}
            {{- if eq $mount.enabled true }}
            - name: frontend-{{ $mountName }}
              persistentVolumeClaim:
                claimName: {{ $.Release.Name }}-{{ $mountName }}
            {{- end }}
            {{- end }}
            {{- end }}
          restartPolicy: OnFailure
---
{{- end }}
{{- end }}
{{- end }}
